[project]
name = "ngio-helpers"
version = "0.2.0"
description = "Custom extensions and iterators for the NGIO ecosystem (OME-Zarr plates/wells)"
requires-python = ">=3.9"
dependencies = [
    "ngio",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]